### ISSUE TITLE
大神,如果可以读出声就更完美了

### ISSUE THREAD

**Issue by doujanbo** [iamcco/dict.vim#1]
插件很好用

**Comment by Cuick** [comment]
发音估计不好整，vim有没有发音的接口不知道，这个插件基于有道的api，这api没有返回发音。音标倒是可以加上。

**Comment by iamcco** [comment]
要加上朗读的话，第一需要音频来源，不知道有道api是否支持，第二个是需要可以播放声音的外部依赖支持，确实不好整，有时间再看看能不能搞

**Comment by xiexiaoy** [comment]
我看到许多单词的查询都返回了美音和英音，没有加上音标是出于什么考虑？
