### ISSUE TITLE
今天刚安装的Dict xxx  openapi 返回异常

### ISSUE THREAD

**Issue by itgoyo** [iamcco/dict.vim#6]
今天刚安装的Dict xxx  openapi 返回异常，请问是接口不能使用了么，还是key的问题？

**Comment by iamcco** [comment]
有时候接口会达到最大使用次数限制，但是我目前测试是 OK 的。你看下报的什么error，或者试下 vim 能不能联网：
vim 支持 python2:
```
:py import urllib2
:py print(urllib2.urlopen('http://baidu.com').read())
```
vim 支持 python3:
```
:py3 import urllib.request
:py3 print(urllib.request.urlopen('http://baidu.com').read())
```
看下能正确返回吗？

**Comment by itgoyo** [comment]
我使用的是python2，返回
```
<html>
<meta http-equiv="refresh" content="0;url=http://www.baidu.com/">
<html>
```
这样子应该是能正常返回了对吧

**Comment by iamcco** [comment]
正常返回了，异常报错报的什么错？

**Comment by itgoyo** [comment]
窗口显示的是
`查询失败 有道openapi返回异常`
就只有这么一句话，没看见更多错误信息了，或者我要怎么操作才能看到错误log

**Comment by iamcco** [comment]
更新下插件，然后打开 vim
```
:let g:debug_dict = 1
:Dict xxx
```
看下输出什么

**Comment by itgoyo** [comment]
@iamcco 
![](http://omvbl46i3.bkt.clouddn.com/18-4-12/22885550.jpg)
![](http://omvbl46i3.bkt.clouddn.com/18-4-12/1201029.jpg)
![](http://omvbl46i3.bkt.clouddn.com/18-4-12/16958007.jpg)

我就在.vimc里面填写
```
Plugin 'iamcco/dict.vim'
let g:api_key = "1932136763"
let g:keyfrom = "aioiyuuko"
```
是不是我这样子写漏掉了什么，还是说写错了。

**Comment by itgoyo** [comment]
实在是不好意思，刚刚特意看了一下key的值，发现是我自己使用了自己的key，然后出错了，抱歉，还劳烦你写了测试代码。非常感谢，你的热心帮助。现在已经可以正常查询了。

**Comment by iamcco** [comment]
吼的

**Comment by itgoyo** [comment]
@iamcco hello,我发现了一个问题，之前我只是看到了输出数据，但是如果不是debug模式的话，还是只显示一句话，openapi错误，只有打开debug模式才会返回详细的翻译，但是输出的那句话还是返回错误。
![](http://omvbl46i3.bkt.clouddn.com/c21340f02a447e8d8e6b04ed950b5139.png)
![](http://omvbl46i3.bkt.clouddn.com/08e5035a8533acd2aa4722a3ce8d5752.png)
你看图一，虽然是返回数据了，但是下面还是查询失败，有道openapi返回异常，不好意思下午的时候题兴奋了没发现，晚上回来用自己电脑测的时候才发现。

**Comment by iamcco** [comment]
返回正常应该就是解析json文件出错了，你用的什么版本的python

**Comment by itgoyo** [comment]
我用的python版本是`2.7.10`

**Comment by iamcco** [comment]
奇怪，我也装了2.7.10也没发现问题

**Comment by itgoyo** [comment]
嗯，好哒，谢谢啦，还是可以查得到。
